# --- General Settings ---
model: "FenrirFC"                           # See available models in src/model.py
seed: 0                                     # Random seed for reproducability
device: "auto"                              # "auto", "cuda", "cpu"
num_epochs: 20

# --- Directories ---
data_dir: "data"                            # Relative path to where DVSGesture data is/will be saved
log_dir: "logs"                             # Directory for log files
model_dir: "saved_models"                   # Directory for saved models
export_dir: "export"                        # Directory for FENRIR export
gradient_log_file: "gradient_norms_log.txt" # Name of the gradient log file

# --- Data  Loader ---
dataset:
  batch_size: 64
  num_workers: 2
  frame_length_us: 16600.0                  # 16.6ms for 60fp
  n_timesteps: 180                          # 180 * 16.6ms = 3s
  target_width: 60                          # Dataset will be transformed to target dim
  target_height: 60                         # Dataset will be transformed to target dim
  num_classes: 11                           # 11 for DVS gesture

optimizer:
  type: "Adam"                              # <- Only here for clarity, does NOT affect script
  lr: 0.003
  betas: [0.9, 0.999]

scheduler:
  type: "CosineAnnealingLR"                 # <- Only here for clarity, does NOT affect script
  t_0: 190                                  # 1/2T every 10 epochs
  eta_min: 0

criterion:
  type: "mse_count_loss"                    # <- Only here for clarity, does NOT affect script
  correct_rate: 0.5
  incorrect_rate: 0.1


# --- Quantization ---
fc1_bits: 4
fc2_bits: 4

# --- Convolution Parameters ---
conv1_out: 12
conv2_out: 5
kernel_size: 3

# --- Fully-Connected Parameters ---
fc1_beta: 0.1                               # Initial beta for fc1
fc2_beta: 0.1                               # Initial beta for fc2
fc1_thr: 1.0                                # Initial threshold for fc1
fc2_thr: 1.0                                # Initial threshold for fc2
fc1_multiplier: 10                          # Weight multiplier for fc1
fc2_multiplier: 10                          # Weight multiplier for fc2

# Export parameters
