domain_path: C:\home\university\8-semester\fenrir\vitis\fenrir_zybo\export\fenrir_zybo\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
